### ISSUE TITLE
Serve tools.gbif.org/ws-validurl with HTTPS

### ISSUE THREAD

**Issue by kbraak** [gbif/validurl-ws#1]
During IPT registration, the IPT calls http://tools.gbif.org/ws-validurl to validate its base URL. 

Unfortunately, when the IPT is served with HTTPS this call will generate a `Blocked loading mixed active content` error (see screenshot below). 

To fix this problem, we should serve tools.gbif.org/ws-validurl with HTTPS. 

For backwards compatibility, requests using HTTP (coming from older versions of the IPT) should still be supported and redirect to HTTP.

Until tools.gbif.org/ws-validurl can be served with HTTPS, new IPTs installed with HTTPS cannot be registered unless the user disables protection on the page (a browser setting), although this is not recommended for obvious reasons. 

For the workaround described above to work, IPT v2.3.3 must still make the request with HTTP.  Assuming this issue gets fixes, later versions of the IPT can switch to using a protocol-agnostic URL for the call. 

![screen shot 2016-12-19 at 14 20 31](https://cloud.githubusercontent.com/assets/5981100/21314269/64b7c452-c5f6-11e6-81bb-88dd86cdb678.png)

**Comment by MattBlissett** [comment]
This is now set up: 
* https://tools.gbif.org/ws-validurl/?url=https://ipt.gbif.org
* http://tools.gbif.org/ws-validurl/?url=https://ipt.gbif.org

**Comment by kbraak** [comment]
Thank you very much Matt
